# Scores for HMM: 'NNZHMM_io_reent_hairpin_sigpep.hmg'

query.prf
Seq length: 250
Labeling:
ooooooooooooooooMMMMMMMMMMMMMMMMMMMMMiiiiiiiiiiiMMMMMMMMMMMM
MMMMMMMMMooooooooooooooooooooMMMMMMMMMMMMMMMMMMMMMiiiiMMMMMM
MMMMMMMMMMMMMMMooooooMMMMMMMMMMMMMMMMMMMMMiiiiiiiiiiiiiiiiiM
MMMMMMMMMMMMMMMMMMMMooooooooooMMMMMMMMMMMMMMMMMMMMMiiiiiiiii
iiiiiiiiii

